name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  cross-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gcc
      run: sudo apt install gcc-arm-linux-gnueabihf
    - name: Install target
      run: rustup target install arm-unknown-linux-musleabihf
    - name: Build
      run: cargo build --release --verbose --target arm-unknown-linux-musleabihf --bins --examples
    - name: Package artifacts
      run: ./package.sh release
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: release.tar.gz
